/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "meeting-notes-analyzer",
  "name": "Minutes Miner",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "What did Tom agree to do, and by when?",
      "does": "Looks up Tom's action items and answers."
    },
    {
      "say": "Mark the analytics task as done",
      "does": "Updates the action tracker."
    },
    {
      "say": "Draft the follow-up email",
      "does": "Writes the recap from the minutes."
    }
  ]
};
