/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "meeting-notes-analyzer",
  "name": "Minutes Miner",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "What did Tom agree to do, and by when?",
      "does": "Looks up Tom's action items and answers."
    },
    {
      "say": "Mark the analytics task as done",
      "does": "Updates the action tracker."
    },
    {
      "say": "Draft the follow-up email",
      "does": "Writes the recap from the minutes."
    }
  ]
};
